export const products = [
  { value: "1", label: "Mujer CON CONSUMISIÓN" },
  { value: "2", label: "Hombre CON CONSUMISIÓN" },
  { value: "3", label: "Mujer SIN Consumision" },
  { value: "4", label: "Hombre SIN Consumision" },
  { value: "5", label: "Hombre FREE" },
  { value: "6", label: "Mujer FREE" },
  { value: "7", label: "RESTO Mujer" },
  { value: "8", label: "RESTO Hombre" },
  { value: "9", label: "LIVING Mujer" },
  { value: "10", label: "LIVING Hombre" },
  { value: "11", label: "VIP Mujer" },
  { value: "12", label: "VIP Hombre" },
  { value: "13", label: "CHILL Mujer" },
  { value: "14", label: "CHILL Hombre" },
  { value: "15", label: "RECEPCION Mujer" },
    { value: "16", label: "RECEPCION Hombre" },
   { value: "17", label: "ANTICIPADA Mujer" },
  { value: "18", label: "ANTICIPADA Hombre" }
];